### ISSUE TITLE
Use Flamingo_Inbound_Message::find()

### ISSUE THREAD

**Issue by takayukister** [takayukister/flamingo#10]
Related issue: #2

You can use `Flamingo_Inbound_Message::find()` to improve drastically some inefficient parts seen in `flamingo_schedule_move_trash()`.

1. In the SQL query in `flamingo_schedule_move_trash()`, there are no post_type and post_status specified. If by any chance another plugin or WordPress itself uses the same meta key '_spam_meta_time', it will lead to a severe conflict.
2. The meta value '_spam_meta_time' remains after the post is trashed, so the post will be included in the result of the SQL query repeatedly.
3. No upper limit of posts is specified in the SQL query, so it might be an abnormally large number causing a time-out.

You can use `Flamingo_Inbound_Message::find()` like this:

```
function flamingo_schedule_move_trash() {

	// abort if FLAMINGO_MOVE_TRASH_DAYS is set to zero or in minus
	if ( (int) FLAMINGO_MOVE_TRASH_DAYS <= 0 ) {
		return true;
	}

	$posts_to_move = Flamingo_Inbound_Message::find( array(
		'posts_per_page' => 100,
		'meta_key' => '_spam_meta_time',
		'meta_value' => time() - ( DAY_IN_SECONDS * FLAMINGO_MOVE_TRASH_DAYS ),
		'meta_compare' => '<',
		'post_status' => Flamingo_Inbound_Message::spam_status,
	) );

	foreach ( $posts_to_move as $post ) {

		if ( $post->trash() ) {
			// delete spam meta time to stop trashing in cron job
			delete_post_meta( $post->id, '_spam_meta_time' );
		}

	}
}
```

It is advisable to avoid using SQL where possible.

**Comment by itpixelz** [comment]
Acted the same as suggested and created a PR #11
