### ISSUE TITLE
Update readme.txt for 2.1 release

### ISSUE THREAD

**Issue by takayukister** [takayukister/flamingo#12]
Update readme.txt following the [Plugin Handbook](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/).

Usually you only need to update 3 numbers in the header section ("Requires at least", "Tested up to", and "Stable tag") and the Changelog section.

Note:

- "Tested up to" should refer to the major version number of WordPress, so it should be "5.2" now (not "5.2.3").
- You don't have to keep old change-logs. Keeping ones for the current major version and last one major version is enough. So, it's OK to remove the change-log for 1.9.

**Comment by itpixelz** [comment]
I have updated readme.txt #13
