### ISSUE TITLE
Export is showing date in UTC (not local) time

### ISSUE THREAD

**Issue by Zodiac1978** [takayukister/flamingo#54]
First reported here: https://wordpress.org/support/topic/export-is-showing-date-in-utc-not-local-time/

I was wondering that the CSV shows UTC time instead of local time, although the list table is showing a local time.

After digging in the code I found get_post_time in `/admin/admin.php` wit the GMT parameter set to true:
`$row[] = get_post_time( 'c', true, $item->id ); // Date`

I think the second parameter (GMT) should be changed to false to switch to local time (or you could add a filter, so we could easily change it if needed without breaking running workflows).

As an alternative you could add another column and add local time there to not break backwards compatibility.

Related: https://developer.wordpress.org/reference/functions/get_post_time/

Thanks for considering!

**Comment by takayukister** [comment]
Thanks for reporting this and sorry for being late.

**Comment by Zodiac1978** [comment]
> Thanks for reporting this and sorry for being late.

No problem and thank you for merging!
