### ISSUE TITLE
CSV export by URL (with E-Mail notifications)

### ISSUE THREAD

**Issue by benjaminpick** [takayukister/flamingo#80]
I would like to use Flamingo so that users without a login can download a current CSV file of one CF7 form. I would send you a pull request. Do you want to incorporate it into your plugin or should I create a new plugin and (if needed) send you a pull request for new filters/hooks?

Here is my implementation plan for now (if you have thoughts about it, please let me know):

Extra "Additional Settings" of the CF7 Form:
* [ ] `flamingo_export_notify_email: email1@example.org, email2@example.org`
* [ ] `flamingo_access_token: ad43dadg234akogngw`
* [ ] `flamingo_access_token_expires: 2021-09-01 10:00:00 GMT`
* [ ] `flamingo_access_token` and `flamingo_access_token_expires` are generated automatically if not present and flamingo_export_notify_email is not empty. (Users can change it manually afterwards if they want, and the expiry time uses a wordpress filter to allow custom values, by default maybe 7 days.)

At form submission, an E-Mail is sent that contains:
* [ ] the name of the form
* [ ] the number of entries that are stored for this form
* [ ] a link to the CSV export
* [ ] the date how long this link is valid

When the URL is called:
* [ ] If the access token is valid, matches the form id in the URL & is not expired: send the CSV file
* [ ] If the access token is not valid or expired: Show an error page: "The access token is invalid. A reminde E-Mail with the valid access token has been sent to the given E-Mail adress." 
(For security reasons, the E-Mail adress can only be changed in the CF7 form itself.)

**Comment by takayukister** [comment]
I'm not interested in this idea, so feel free to implement it as your original plugin.
