### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Bronxphoneix** [takayukister/flamingo#90]
![image](https://user-images.githubusercontent.com/43340706/155000900-0be5827d-2d56-434d-9e1a-4cceb283d1fc.png)

I see a typo. flamigo is written instead of flamingo, language is Turkish

**Comment by Zodiac1978** [comment]
Maybe the location is invalid, but the typo is not. It is wrongly translated:
https://translate.wordpress.org/projects/wp-plugins/flamingo/stable/tr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=845988&filters%5Btranslation_id%5D=24583049

As I am not a translation editor for Turkish, I can only suggest a new translation (as everyone else). It must be validated from the Turkish translation team.
